const flightsData = [
  {
    id: 1,
    origin: "Dallas",
    destination: "Chicago",
    airline: "Delta",
    date: "2024-03-31",
    time: "08:00",
    carbonEmission: 150,
    price: 900,
  },
  {
    id: 2,
    origin: "Dallas",
    destination: "Chicago",
    airline: "United",
    date: "2024-03-31",
    time: "09:40",
    carbonEmission: 167,
    price: 880,
  },
  {
    id: 3,
    origin: "Dallas",
    destination: "Chicago",
    airline: "Americal Airlines",
    date: "2024-03-31",
    time: "13:05",
    carbonEmission: 170,
    price: 850,
  },
  {
    id: 4,
    origin: "Dallas",
    destination: "Chicago",
    airline: "Americal Airlines",
    date: "2024-03-31",
    time: "13:05",
    carbonEmission: 210,
    price: 830,
  },
  {
    id: 5,
    origin: "Dalles",
    destination: "Chicago",
    airline: "Americal Airlines",
    date: "2024-03-31",
    time: "13:05",
    carbonEmission: 250,
    price: 810,
  },
  {
    id: 6,
    origin: "Dallas",
    destination: "Chicago",
    airline: "Americal Airlines",
    date: "2024-03-31",
    time: "13:05",
    carbonEmission: 290,
    price: 790,
  },
  {
    id: 7,
    origin: "Dallas",
    destination: "Chicago",
    airline: "Americal Airlines",
    date: "2024-03-31",
    time: "13:05",
    carbonEmission: 300,
    price: 750,
  },
  {
    id: 8,
    origin: "Dallas",
    destination: "Chicago",
    airline: "Americal Airlines",
    date: "2024-03-31",
    time: "13:05",
    carbonEmission: 380,
    price: 710,
  },
];

export default flightsData;
